#use_frameworks!
source 'https://github.com/rocedar/RocedarPodSpecs.git'
source 'https://github.com/CocoaPods/Specs.git'

target 'RCNIMAVChatComponet_Example' do
  pod 'RCNIMAVChatComponet', :path => '../'

  target 'RCNIMAVChatComponet_Tests' do
    inherit! :search_paths

    
  end
end
